[project]
name = "pokemon"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pygame-ce>=2.5.5",
    "pytmx>=3.32",
    "setuptools>=80.9.0",
]
